### Numpy basics

1\. Find the row, column and overall means for the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [19]:
import numpy as np #import np library
m0=np.arange(12) #m0 is a 1D array filled with integer numbers in range 12 (e.g. from 0-11)
print(m0)
print("rank:",m0.ndim,",shape (nrows,ncols):",m0.shape,"type:",m0.dtype,"\n")

 
m=m0.reshape((3,4))
print(m) #reshape arrange the 1D array into a 2D array (a matrix) with 3 rows, 4 colums
print("rank:",m.ndim,",shape (nrows,ncols):",m.shape,"type:",m0.dtype)




[ 0  1  2  3  4  5  6  7  8  9 10 11]
rank: 1 ,shape (nrows,ncols): (12,) type: int64 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
rank: 2 ,shape (nrows,ncols): (3, 4) type: int64


notes about arange
arange(stop): Values are generated within the half-open interval [0, stop)
(in other words, the interval including start but excluding stop).
see documentation

https://numpy.org/doc/stable/reference/generated/numpy.arange.html

numpy.reshape    

https://numpy.org/doc/stable/reference/generated/numpy.reshape.html?highlight=reshape    

2\. Find the outer product of the following two vecotrs

```python
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])
```

Do this in the following ways:

   * Using the function outer in numpy
   * Using a nested for loop or list comprehension
   * Using numpy broadcasting operatoins


**outer function**

https://numpy.org/doc/stable/reference/generated/numpy.outer.html?highlight=outer#numpy.outer

https://www.geeksforgeeks.org/numpy-outer-function-python/

tile

https://numpy.org/doc/stable/reference/generated/numpy.tile.html?highlight=tile#numpy.tile

broadcasting

https://numpy.org/doc/stable/user/basics.broadcasting.html

https://stackoverflow.com/questions/29241056/how-do-i-use-np-newaxis

https://numpy.org/doc/1.20/user/theory.broadcasting.html

In [109]:
#outer product= product of u x (v)^T 
#out[i, j] = u[i] * b[j]
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])
print("u:",u)
print("v:",v)

#using outer function
k=np.outer(u,v)
print("using numpy outer:")
print("u x v:\n",k,"\n")

#list comprehension
print("using list comprehension:")
outp = np.array([u[i]*v[j] for i in range(len(u)) for j in range(len(v))])#.reshape((len(u),len(v)))
outp=outp.reshape((len(u),len(v)))
print(outp, '\n')

#nested loop
print("using nested loop:")

l=[]
for i in range(len(u)):
    for j in range(len(v)):
        l.append(u[i]*v[j])
#print(l)        
w=np.array(l).reshape(len(u),len(v))
print(w)

#Using numpy broadcasting operations
print("using numpy broadcasting operations 1:")

#tile makes tot copies of vector u, according to a matrix (len(u),len(u))
#then it is transposed
mu=np.tile(u,(len(u),1)).T
print("tiled_u \n",mu)
mv=np.tile(v,(len(v),1))
print("tiled_v_Transposed \n",mv)
prod=mu*mv #element wise product
print("u*vT \n",prod,"\n")


print("using numpy broadcasting operations 2:")

#Here the newaxis index operator inserts a new axis into the vectors, u,v, making them a two-dimensional 4x1 and 1x4 array

# make it as column vector by inserting an axis along second dimension
col_vec = u[:, np.newaxis]     # arr[:, None]
print("defining a column vector")
print(col_vec,"\n","shape",col_vec.shape)

# make it as row vector by inserting an axis along first dimension
row_vec = v[np.newaxis, :]     # arr[None, :]
print("defining a row vector")
print(row_vec,"\n","shape",row_vec.shape)

print(row_vec*col_vec)

u: [1 3 5 7]
v: [2 4 6 8]
using numpy outer:
u x v:
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]] 

using list comprehension:
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]] 

using nested loop:
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]
using numpy broadcasting operations 1:
tiled_u 
 [[1 1 1 1]
 [3 3 3 3]
 [5 5 5 5]
 [7 7 7 7]]
tiled_v_Transposed 
 [[2 4 6 8]
 [2 4 6 8]
 [2 4 6 8]
 [2 4 6 8]]
u*vT 
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]] 

using numpy broadcasting operations 2:
defining a column vector
[[1]
 [3]
 [5]
 [7]] 
 shape (4, 1)
defining a row vector
[[2 4 6 8]] 
 shape (1, 4)
[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. Create a 10 by 6 matrix of random uniform numbers. Set all rows with any entry less than 0.1 to be zero

Hint: Use the following numpy functions - np.random.random, np.any as well as Boolean indexing and the axis argument.

ABOUT ANY

https://www.sharpsightlabs.com/blog/numpy-any/

If you use np.any() on an array with boolean values, the function will test if any of the elements are True. 

if you have a 2D array and you set axis = 1, the function will operate horizontally along axis-1. This effectively applies the function across the rows.

if you have a 2D array and you set axis = 0, the function will operate downward along axis-0. This effectively applies the function down the columns.

In [175]:
#10x6 matrix
import numpy.random as npr
npr.seed(123)#fix the seed for reproducible results

mat = np.array([npr.rand() for i in range(10*6)]).reshape((10,6))
print(mat)

print("\n fast way \n")
mat2=npr.rand(10,6) #rand uniform distribution between 0-1, to fill a 10x6 matrix
print(mat2)

mask=(mat2<=0.1)
print("the mask:",mask,"\n")
filt_mat=mat2[mask]
print("filtered:\n",filt_mat)

k=np.any(mask,axis=1,keepdims=True) #if at least one entry is <=0.1 returns TRUE
print(k)
k=np.array(k)
#k=k[:, np.newaxis]
#k=np.tile(k,(1,6))
#print(k)
k=k.astype(int)
k=np.logical_not(k) #For each line with at least 1 entry <=0 returns FALSE==0
print("shape k",k.shape,"\n",k)
print("shape m",mat2.shape,"\n",mat2)
print("final matrix, filtered")
print(k*mat2) #element wise product with broadcasting of klines (imposing same value)
#each line with no small entries remains the same (*1) while the other becomes 0

#print(mat2*k)
#mat2[k]
#print("new mat2 \n",mat2)

#print(np.any(mat2<=0))

[[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897 0.42310646]
 [0.9807642  0.68482974 0.4809319  0.39211752 0.34317802 0.72904971]
 [0.43857224 0.0596779  0.39804426 0.73799541 0.18249173 0.17545176]
 [0.53155137 0.53182759 0.63440096 0.84943179 0.72445532 0.61102351]
 [0.72244338 0.32295891 0.36178866 0.22826323 0.29371405 0.63097612]
 [0.09210494 0.43370117 0.43086276 0.4936851  0.42583029 0.31226122]
 [0.42635131 0.89338916 0.94416002 0.50183668 0.62395295 0.1156184 ]
 [0.31728548 0.41482621 0.86630916 0.25045537 0.48303426 0.98555979]
 [0.51948512 0.61289453 0.12062867 0.8263408  0.60306013 0.54506801]
 [0.34276383 0.30412079 0.41702221 0.68130077 0.87545684 0.51042234]]

 fast way 

[[0.66931378 0.58593655 0.6249035  0.67468905 0.84234244 0.08319499]
 [0.76368284 0.24366637 0.19422296 0.57245696 0.09571252 0.88532683]
 [0.62724897 0.72341636 0.01612921 0.59443188 0.55678519 0.15895964]
 [0.15307052 0.69552953 0.31876643 0.6919703  0.55438325 0.38895057]
 [0.92513249 0.84167

4\. Use np.linspace to create an array of 100 numbers between 0 and 2π (includsive).

  * Extract every 10th element using slice notation
  * Reverse the array using slice notation
  * Extract elements where the absolute difference between the sine and cosine functions evaluated at that element is less than 0.1
  * Make a plot showing the sin and cos functions and indicate where they are close

5\. Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anto-diagonal (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagnoal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

6\. Use broadcasting to create a grid of distances

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles
The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Construct a 2D grid of distances among each city along Route 66
  * Convert that in km (those savages...)

7\. Prime numbers sieve: compute the prime numbers in the 0-N (N=99 to start with) range with a sieve (mask).
  * Constract a shape (100,) boolean array, the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (timeit); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

**N.B. the following exercises are meant to be solved only if you are familiar with the numpy random library. If not you can skip them (postponed for one of the next exercise sessions)**


8\. Diffusion using random walk

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of a random walker after a given amount of time. 
To do that, let's simulate many walkers and create a 2D array with each walker as a raw and the actual time evolution as columns

  * Take 1000 walkers and let them walk for 200 steps
  * Use randint to create a 2D array of size walkers x steps with values -1 or 1
  * Build the actual walking distances for each walker (i.e. another 2D array "summing on each raw")
  * Take the square of that 2D array (elementwise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * Plot the average distances (sqrt(distance\*\*2)) as a function of time (step)
  
Did you get what you expected?

9\. Analyze a data file 
  * Download the population of hares, lynxes and carrots at the beginning of the last century.
    ```python
    ! wget https://www.dropbox.com/s/3vigxoqayo389uc/populations.txt
    ```

  * Check the content by looking within the file
  * Load the data (use an appropriate numpy method) into a 2D array
  * Create arrays out of the columns, the arrays being (in order): *year*, *hares*, *lynxes*, *carrots* 
  * Plot the 3 populations over the years
  * Compute the main statistical properties of the dataset (mean, std, correlations, etc.)
  * Which species has the highest population each year?

Do you feel there is some evident correlation here? [Studies](https://www.enr.gov.nt.ca/en/services/lynx/lynx-snowshoe-hare-cycle) tend to believe so.