# OSEMN Exercises

**One of these excercises will be at the exam!!**


In [1]:
%matplotlib inline
import pandas as pd
import numpy as np

1\. Create a random list of number and then save it to a text file named "simple_data.txt"

In [26]:
import numpy.random as npr
import sys
num=npr.randint(10,30)
print(num)
#list=np.array([npr.rand() for i in range(num)])
list2=[npr.rand() for i in range(num)]
#print(list,len(list))
print(list2,len(list2))

f=open("simple_data.txt","w")

for n in list2:
    f.write("%s \n" %n)
f.close()


17
[0.6519926439051965, 0.05787546918787034, 0.7270669047669789, 0.27321981012403784, 0.7237242327417645, 0.9310277487739684, 0.6494821665766228, 0.8839274477275771, 0.9279997215063868, 0.4059267858953023, 0.08566492009095061, 0.12617551403974414, 0.701349032707355, 0.22675627013170374, 0.9613526436249304, 0.7723913655979069, 0.6847118225283289] 17


In [24]:
!ls
!cat simple_data.txt

00ex_introduction.ipynb		 cases_vs_searches.jpeg
00_introduction.ipynb		 data.h5
01ex_Fundamentals.ipynb		 example.hdf5
01_Fundamentals.ipynb		 example.json
02ex_NumberRepresentation.ipynb  numpy_broadcasting.png
02_NumberRepresentation.ipynb	 numpy_fancy_indexing.png
03_Bash.ipynb			 numpy_indexing.png
03ex_Bash.ipynb			 populations.txt
04ex_Numpy.ipynb		 README_GitInstructions.md
04_Numpy.ipynb			 README.md
05ex_OSEMN.ipynb		 simple_data.txt
05_OSEMN.ipynb
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0


2\. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [29]:
mat=np.random.randint(10,size=(5,5))
print(mat)

[[0 8 5 8 7]
 [0 8 4 3 2]
 [0 0 4 7 4]
 [9 0 3 9 5]
 [3 7 0 2 8]]


In [31]:

f1=open("data.txt","w")

for n in mat:
    f1.write("%s \n" %n)
f1.close()

In [41]:
with open("data2.txt" , 'wb') as f2:
    np.savetxt(f2, mat, delimiter=' ', newline='\n', header='', footer='', comments='# ')


https://stackoverflow.com/questions/43133056/saving-numpy-array-to-a-file-without-brackets-and-white-spaces

https://numpy.org/doc/stable/reference/generated/numpy.savetxt.html

https://www.w3schools.com/python/numpy/numpy_array_iterating.asp

In [42]:
!cat data.txt
!cat data2.txt

[0 8 5 8 7] 
[0 8 4 3 2] 
[0 0 4 7 4] 
[9 0 3 9 5] 
[3 7 0 2 8] 
0.000000000000000000e+00 8.000000000000000000e+00 5.000000000000000000e+00 8.000000000000000000e+00 7.000000000000000000e+00
0.000000000000000000e+00 8.000000000000000000e+00 4.000000000000000000e+00 3.000000000000000000e+00 2.000000000000000000e+00
0.000000000000000000e+00 0.000000000000000000e+00 4.000000000000000000e+00 7.000000000000000000e+00 4.000000000000000000e+00
9.000000000000000000e+00 0.000000000000000000e+00 3.000000000000000000e+00 9.000000000000000000e+00 5.000000000000000000e+00
3.000000000000000000e+00 7.000000000000000000e+00 0.000000000000000000e+00 2.000000000000000000e+00 8.000000000000000000e+00


3\. Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [48]:
data_mat= np.loadtxt('data2.txt')
print(data_mat)

with open("data2_mod.txt" , 'wb') as f2:
    np.savetxt(f2, mat, delimiter=',', newline='\n', header='', footer='', comments='# ')

[[0. 8. 5. 8. 7.]
 [0. 8. 4. 3. 2.]
 [0. 0. 4. 7. 4.]
 [9. 0. 3. 9. 5.]
 [3. 7. 0. 2. 8.]]


In [72]:
f3=open("data3.txt","w")

for n in data_mat:
    for y in n:
        if y!=n[len(n)-1]:
            f3.write("%s," %y)
        else:f3.write("%s" %y)                 
    f3.write('\n')
f3.close()

In [73]:
!cat data2_mod.txt
!cat data3.txt

0.000000000000000000e+00,8.000000000000000000e+00,5.000000000000000000e+00,8.000000000000000000e+00,7.000000000000000000e+00
0.000000000000000000e+00,8.000000000000000000e+00,4.000000000000000000e+00,3.000000000000000000e+00,2.000000000000000000e+00
0.000000000000000000e+00,0.000000000000000000e+00,4.000000000000000000e+00,7.000000000000000000e+00,4.000000000000000000e+00
9.000000000000000000e+00,0.000000000000000000e+00,3.000000000000000000e+00,9.000000000000000000e+00,5.000000000000000000e+00
3.000000000000000000e+00,7.000000000000000000e+00,0.000000000000000000e+00,2.000000000000000000e+00,8.000000000000000000e+00
0.0,8.0,5.0,8.0,7.0
0.0,8.0,4.0,3.0,2.0
0.0,0.0,4.07.0,4.0
9.0,0.0,3.0,9.0,5.0
3.0,7.0,0.0,2.0,8.0


4\. load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding


4bit at the end of each LINE must be ignored!!
**hint**: use the `chr()` function to convert a number to a char

In [32]:
import struct

with open("credit_card.dat",'rb') as file:
    file_content=file.read()
    num_counter=0
    num_size=6
    
    thisInt = struct.unpack("H", file_content[0:6])
#    for i in range(0, len(file_content),num_size):
 #       thisInt = struct.unpack('', file_content[i:i+num_size+4])[0]

                                
    file.close()
print(num_counter)

error: unpack requires a buffer of 2 bytes

5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the istogram of the 'class' field. Decribe wath yuou see


7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

8\. Load the same file of point 6, and convert the file to json with Pandas.